"""
Markdown exporter for research results.

LEARNING NOTE - Markdown Export:
Markdown is a lightweight markup language. It's perfect for:
- Documentation (README files, wikis)
- GitHub/GitLab display
- Converting to other formats (HTML, PDF)
- Human-readable with formatting
"""

from datetime import datetime
from typing import TYPE_CHECKING

from .base import BaseExporter, ExportFormat

if TYPE_CHECKING:
    from ..agents.research_agent import ResearchResult


class MarkdownExporter(BaseExporter):
    """
    Export research results as Markdown.

    Produces clean, readable Markdown perfect for:
    - GitHub documentation
    - Note-taking apps (Obsidian, Notion)
    - Converting to PDF/HTML
    - Sharing with team members
    """

    format = ExportFormat.MARKDOWN
    extension = "md"

    def __init__(self, include_toc: bool = True, include_metadata: bool = True):
        """
        Initialize Markdown exporter.

        Args:
            include_toc: If True, add table of contents
            include_metadata: If True, add research metadata section
        """
        self.include_toc = include_toc
        self.include_metadata = include_metadata

    def _format_content(self, result: "ResearchResult") -> str:
        """Convert research result to Markdown string."""
        lines = []

        # Title
        lines.append(f"# Research: {result.query}")
        lines.append("")

        # Metadata badge
        status = "Complete" if result.completed else "Partial"
        lines.append(f"> **Status:** {status} | "
                     f"**Iterations:** {result.iterations} | "
                     f"**Sources:** {len(result.sources)} | "
                     f"**Cost:** ${result.usage.cost_usd:.4f}")
        lines.append("")

        # Table of contents
        if self.include_toc:
            lines.append("## Table of Contents")
            lines.append("- [Summary](#summary)")
            if result.key_findings:
                lines.append("- [Key Findings](#key-findings)")
            lines.append("- [Sources](#sources)")
            if not result.extracted_data.is_empty():
                lines.append("- [Extracted Data](#extracted-data)")
            if self.include_metadata:
                lines.append("- [Metadata](#metadata)")
            lines.append("")

        # Summary
        lines.append("## Summary")
        lines.append("")
        lines.append(result.summary)
        lines.append("")

        # Key Findings
        if result.key_findings:
            lines.append("## Key Findings")
            lines.append("")
            for finding in result.key_findings:
                lines.append(f"- {finding}")
            lines.append("")

        # Sources
        lines.append("## Sources")
        lines.append("")
        if result.sources:
            for i, source in enumerate(result.sources, 1):
                title = source.get("title", "Untitled")
                url = source.get("url", "")
                lines.append(f"{i}. [{title}]({url})")
        else:
            lines.append("*No sources were fetched during research.*")
        lines.append("")

        # Extracted Data
        if not result.extracted_data.is_empty():
            lines.append("## Extracted Data")
            lines.append("")
            self._add_extracted_data(lines, result.extracted_data)

        # Metadata
        if self.include_metadata:
            lines.append("## Metadata")
            lines.append("")
            lines.append("| Property | Value |")
            lines.append("|----------|-------|")
            lines.append(f"| Query | {result.query} |")
            lines.append(f"| Model | {result.usage.model} |")
            lines.append(f"| Iterations | {result.iterations} |")
            lines.append(f"| Input Tokens | {result.usage.input_tokens:,} |")
            lines.append(f"| Output Tokens | {result.usage.output_tokens:,} |")
            lines.append(f"| Total Tokens | {result.usage.total_tokens:,} |")
            lines.append(f"| Cost (USD) | ${result.usage.cost_usd:.4f} |")
            lines.append(f"| Exported | {datetime.now():%Y-%m-%d %H:%M:%S} |")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("*Generated by Research Bot*")

        return "\n".join(lines)

    def _add_extracted_data(self, lines: list[str], data) -> None:
        """Add extracted data sections to markdown."""
        # Statistics
        if data.statistics:
            lines.append("### Statistics")
            lines.append("")
            for stat, context in list(data.statistics.items())[:10]:
                lines.append(f"- **{stat}**: {context}")
            lines.append("")

        # Specifications
        if data.specifications:
            lines.append("### Technical Specifications")
            lines.append("")
            lines.append("| Specification | Value |")
            lines.append("|---------------|-------|")
            for key, value in data.specifications.items():
                lines.append(f"| {key} | {value} |")
            lines.append("")

        # Versions
        if data.versions:
            lines.append("### Version Numbers")
            lines.append("")
            for version in data.versions[:10]:
                lines.append(f"- {version}")
            lines.append("")

        # Dates
        if data.dates:
            lines.append("### Dates Mentioned")
            lines.append("")
            for date in data.dates[:10]:
                lines.append(f"- {date}")
            lines.append("")

        # Prices
        if data.prices:
            lines.append("### Pricing")
            lines.append("")
            lines.append("| Item | Price |")
            lines.append("|------|-------|")
            for item, price in data.prices.items():
                lines.append(f"| {item} | {price} |")
            lines.append("")

        # Code Snippets
        if data.code_snippets:
            lines.append("### Code Snippets")
            lines.append("")
            for snippet in data.code_snippets[:5]:
                lang = snippet.get("language", "")
                code = snippet.get("code", "")
                lines.append(f"```{lang}")
                lines.append(code)
                lines.append("```")
                lines.append("")

        # Entities
        if data.entities:
            lines.append("### Key Entities Mentioned")
            lines.append("")
            lines.append(", ".join(data.entities[:15]))
            lines.append("")
